name: merchant_pos_flutter
description: Merchant POS Flutter App
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: '>=3.0.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  dio: ^5.4.0
  flutter_secure_storage: ^9.0.0
  qr_flutter: ^4.1.0
  intl: ^0.19.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0
  flutter_launcher_icons: ^0.13.1

flutter_launcher_icons:
  android: true
  ios: true
  image_path: "assets/icon/origami-pos.png"
  adaptive_icon_background: "#000000"
  adaptive_icon_foreground: "assets/icon/origami-pos.png"

flutter:
  uses-material-design: true
  assets:
    - assets/icon/
