global:
  scrape_interval: 15s
  evaluation_interval: 15s

scrape_configs:
  - job_name: 'user-bff'
    metrics_path: '/actuator/prometheus'
    static_configs:
      - targets: ['user-bff:8080']

  - job_name: 'admin-bff'
    metrics_path: '/actuator/prometheus'
    static_configs:
      - targets: ['admin-bff:8083']

  - job_name: 'merchant-bff'
    metrics_path: '/actuator/prometheus'
    static_configs:
      - targets: ['merchant-bff:8084']

  - job_name: 'benefits-core'
    metrics_path: '/actuator/prometheus'
    static_configs:
      - targets: ['benefits-core:8091']

  - job_name: 'postgres'
    static_configs:
      - targets: ['postgres:5432']
