global:
  scrape_interval: 15s
  evaluation_interval: 15s

scrape_configs:
  - job_name: 'prometheus'
    static_configs:
      - targets: ['localhost:9090']

  - job_name: 'tenant-service'
    metrics_path: '/actuator/prometheus'
    static_configs:
      - targets: ['localhost:8090']

  - job_name: 'benefits-core'
    metrics_path: '/actuator/prometheus'
    static_configs:
      - targets: ['localhost:8091']

  - job_name: 'payments-orchestrator'
    metrics_path: '/actuator/prometheus'
    static_configs:
      - targets: ['localhost:8092']

  - job_name: 'merchant-service'
    metrics_path: '/actuator/prometheus'
    static_configs:
      - targets: ['localhost:8093']

  - job_name: 'support-service'
    metrics_path: '/actuator/prometheus'
    static_configs:
      - targets: ['localhost:8094']

  - job_name: 'audit-service'
    metrics_path: '/actuator/prometheus'
    static_configs:
      - targets: ['localhost:8095']
