spring:
  profiles:
    active: local
  application:
    name: merchant-bff
  webflux:
    base-path: /
  r2dbc:
    url: r2dbc:postgresql://benefits-postgres:5432/benefits
    username: benefits
    password: benefits123
    pool:
      initial-size: 10
      max-size: 20
      max-idle-time: 30m
      max-acquire-time: 2s
      validation-query: SELECT 1
  datasource:
    hikari:
      connection-timeout: 10000
  jackson:
    serialization:
      write-dates-as-timestamps: false
  jpa:
    database: postgresql
    hibernate:
      ddl-auto: validate

server:
  port: 8084
  shutdown: graceful
  netty:
    connection-timeout: 10000ms
    idle-timeout: 60000ms

logging:
  level:
    root: INFO
    com.benefits.merchantbff: DEBUG
    io.r2dbc: DEBUG
    org.springframework.r2dbc: DEBUG

management:
  endpoints:
    web:
      exposure:
        include: health,info,metrics,prometheus
  endpoint:
    health:
      show-details: always

springdoc:
  api-docs:
    path: /api/v1/docs
  swagger-ui:
    path: /swagger-ui.html
    enabled: true
