spring:
  cloud:
    compatibility-verifier:
      enabled: false
  jpa:
    show-sql: false

logging:
  level:
    root: INFO
    com.benefits.merchantbff: DEBUG

core:
  service:
    url: http://benefits-core:8091
    api-key: core-service-secret-key

# URLs dos servi√ßos especializados
paymentsorchestrator:
  service:
    url: http://payments-orchestrator:8092
acquireradapter:
  service:
    url: http://acquirer-adapter:8093
riskservice:
  service:
    url: http://risk-service:8094

