spring:
  cloud:
    compatibility-verifier:
      enabled: false
  jpa:
    show-sql: false

logging:
  level:
    root: INFO
    com.benefits.adminbff: DEBUG

core:
  service:
    url: http://benefits-core:8091
    api-key: core-service-secret-key

# URLs dos servi√ßos especializados
kycservice:
  service:
    url: http://kyc-service:8101
kybservice:
  service:
    url: http://kyb-service:8102
settlementservice:
  service:
    url: http://settlement-service:8096
reconservice:
  service:
    url: http://recon-service:8097
supportservice:
  service:
    url: http://support-service:8095
riskservice:
  service:
    url: http://risk-service:8094
auditservice:
  service:
    url: http://audit-service:8099

